### ISSUE TITLE
Examples in the wild

### ISSUE THREAD

**Issue by hadley** [r-lib/ellipsis#10]
* https://twitter.com/dinga92/status/1102614185459048448
* https://github.com/tidyverse/dplyr/issues/4229

**Comment by jennybc** [comment]
`devtools::install_github()` used to have a `build_vignettes` argument. But its current incarnation, now `remotes::install_github()`, does **not** have this argument. To build vignettes, we're supposed to do this:

```
devtools::install_github("foo/bar", build_opts = c("--no-resave-data", "--no-manual"))
```

as per https://github.com/r-lib/devtools/issues/1896#issuecomment-431834044.

However lots of people still try to do `install_github("foo/bar", build_vignettes = TRUE)` and, no doubt, some of our own material probably shows this, i.e. hasn't been updated yet.

And because the signature of `install_github()` contains `...`, their attempts just silently fail:

```
install_github(repo, ref = "master", subdir = NULL,
  auth_token = github_pat(), host = "api.github.com",
  dependencies = NA, upgrade = c("default", "ask", "always", "never"),
  force = FALSE, quiet = FALSE, build = TRUE,
  build_opts = c("--no-resave-data", "--no-manual",
  "--no-build-vignettes"), repos = getOption("repos"),
  type = getOption("pkgType"), ...)
```

cc @jimhester

**Comment by alexpghayes** [comment]
I can dig up a myriad of examples from `broom` if that would be helpful.

**Comment by jennybc** [comment]
Sure @alexpghayes please add a few.

**Comment by benthestatistician** [comment]
How about `predict(my_glm, data=test)` and `predict(my_glm, new.data=test)`, where `my_glm` is a glm fit to a training data set and `test` is a separate holdout sample. (As opposed to `predict(my_glm, newdata=test)` or `predict(my_glm, test)`.)

**Comment by alexpghayes** [comment]
Perhaps the most concerning has been a couple instances like

```r
tidy(model, conf.int = TRUE, conf.levl = 0.99)
```

I've come across in the wild, where researchers have produced intervals with coverage of 0.95 while believing the coverage is higher. Some examples are collected in https://github.com/tidymodels/broom/issues/413 (these are less explicit than I originally thought).

**Comment by DanielEWeeks** [comment]
For my vignette to build, I had to add the 'build_vignettes = TRUE' option:

`install_github("foo/bar", build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE)`

When I did this;

`install_github("foo/bar", build_opts = c("--no-resave-data", "--no-manual"))`

the vignette did not build.

**Comment by hadley** [comment]
Moved to https://github.com/tidyverse/principles/issues/58
